### ISSUE TITLE
Negative arrival times

### ISSUE THREAD

**Issue by rstpeng** [seanblanchfield/seans-homeassistant-addons#1] opened 2023-11-23 14:16 UTC
This is what my card looks like after following the install. Has anyone else reported similar? 

![image](https://github.com/seanblanchfield/seans-homeassistant-addons/assets/83469269/7d965532-4f72-4be7-8ecd-0b934ada9c81)

**Comment by seanblanchfield** [comment] 2023-11-23 19:24
I've seen something similar but only for a few seconds. If the list of arrivals is out of date, then the custom card code will calculate a negative number of minutes until arrival (time of arrival - now). I notice this when I wake a wall mounted tablet up with motion, and it renders the card with old data for a second or two before it loads new data.

I think I need to filter any arrivals that are in the past in the `render()` function of the custom card. Perhaps I should display a loading indicator instead of the content if the list of arrivals looks like it is out of date.

If what you see doesn't refresh with up-to-date info within a few seconds, perhaps you have another problem too.  I don't suppose you configured the "refresh interval" setting to a very long value? It defaults to 30 seconds.

**Comment by seanblanchfield** [comment] 2023-11-23 19:36
Actually, I just encountered a similar problem. The addon has stopped updating the HS sensor entities. Restarting the addon resolved the issue. I'll look into the reasons for this, but can you confirm if it's the same for you?

**Comment by rstpeng** [comment] 2023-11-23 22:15
Restarting the add on corrects the times for me. I left the refresh at the default. Great addon BTW.

**Comment by seanblanchfield** [comment] 2023-11-28 21:31
I believe this bug has happened to me once, and while investigating it I confirmed that the main server process (the TFI-GTFS python server) was running fine, and could be queried for stops. The problem seemed to be in the addon's `run.sh` bash script, which is responsible for polling the server process for upcoming arrivals and writing the results into HA entities. I suspect that something crashed the infinite loop in the `update_sensors()` function in that bash script. I've added some addition logging to my local version and will look more closely if it happens again.

**Comment by seanblanchfield** [comment] 2023-12-12 08:50
I think I caught this bug red-handed, so to speak. It took 2 weeks for it to happen again. Here's some log output from the add-on at the point that it occurs. The `Updated sensor.tfi_gtfs_stop_NNNN` stuff is additional debug output I added. The problem occurs when these messages stop being output, near the top of the log snippet below. It seems to have been precipitated by the python app not handling an unexpected response from the TFI server. Pasting here for my own reference. I'll work on fixing this as soon as I have time. 

Until then, a restart of the add-on resolves the problem.

```
DEBUG:root:Live feed updated.
Updated sensor.tfi_gtfs_stop_2189
Updated sensor.tfi_gtfs_stop_1409
ERROR:server:Exception on /api/v1/arrivals [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 154, in decorated_function
    response_data = func(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/app/server.py", line 282, in arrivals
    'arrivals': gtfs.get_scheduled_arrivals(stop_number, now, datetime.timedelta(minutes=args.minutes))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/gtfs.py", line 470, in get_scheduled_arrivals
    agency_name = self.store.get('agency', route_info['agency'])
                                           ~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
DEBUG:root:Updating from live feed.
DEBUG:root:Got 899 trip updates, 6618 unrecognised trips, 320 added trips, 0 cancelled trips
DEBUG:root:Live feed updated.
```

**Comment by seanblanchfield** [comment] 2023-12-31 17:53
I think this should be fixed now, after [this commit](https://github.com/seanblanchfield/tfi-gtfs/commit/b5d1b39170a290d3d5865f7a946d4fc7a773fbd6), which guards against unrecognised routes being present in the live data feed, which could cause calls to the server to return a 500 error, which would cause the bash loop in the addon `run.sh` to crash. The error was so intermittent that I'm going to leave this open for a bit until I feel more confident that it doesn't reoccur.

**Closed** 2024-07-04 16:47 UTC
